version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/vue-event-manager

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --pure-lockfile
      - run:
          name: Run ESLint
          command: yarn eslint
      - run:
          name: Run Tests
          command: |
            yarn jest
      - run:
          name: Build Release
          command: yarn build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules